### ISSUE TITLE
Use localhost:5000 instead of registry:5000 as the docker registry

### ISSUE THREAD

**Issue by charypar** [redbadger/stack#8]
Since the registry service running on the swarm is mesh routed, each host can actually point to itself as registry and it solves the problem of routing to the registry through `/etc/hosts`. 

This means even after restarting the machines and losing state in Virtualbox, registry can still be resolved correctly without manual fixes.

This will mean tagging all the images as `localhost:5000/[service]` instead of `registry:5000/[service]`

**Comment by JoeStanton** [comment]
Can't you solve this with an overlay network and use the service discovery to resolve `registry`? Or does that not work because the nodes themselves are not part of overlay networks? (only containers are).

Secondly, what is the benefit of self hosting the registry vs using https://aws.amazon.com/ecr/?

(Just eager to follow your reasoning 🤓)

**Comment by StuartHarris** [comment]
Yep it's the nodes that need access to the registry not the containers and you're right, the overlay networks are only visible as network interfaces inside the container.
The self-hosting of the registry is only to allow the swarm to run on a laptop (but it could easily be a standalone regstry outside the swarm). In AWS, ECR would be a good choice. I think Nexus 3 has a docker registry with upstream passthrough.
